### ISSUE TITLE
Rustfmt always recompiles

### ISSUE THREAD

**Issue by marcusklaas** [nrc/rustfmt#110]
Rustfmt always recompiles on my machine, even if no source code has been altered. Is this happening for other people as well? If so, why does it happen and how can we prevent it?

**Comment by cassiersg** [comment]
It's also happening for me. It seems to be related to the build script. Commenting the line `build=build.rs` prevent the rebuild when nothing has changed. (I don't know why ?)

**Comment by marcusklaas** [comment]
Interesting. Maybe it updates the last edit timestamp on default.toml in the root directory, which could trick Cargo into believing code may have changed?

**Comment by cassiersg** [comment]
Commenting the line `std::fs::copy(in_file, out_file).unwrap();` doesn't change anything. It's maybe a default behavior of Cargo to rebuild everything when there is a build script... needs more investigation.

**Comment by marcusklaas** [comment]
Weird -- commenting out that line does the trick here...

**Comment by cassiersg** [comment]
The source of trouble was a symlink `rustfmt/rustfmt -> rustfmt/target/debug/rustfmt`. Cargo seems to consider all files under `rustfmt/` to decide when to rebuild.

**Comment by marcusklaas** [comment]
Did you create this symlink by hand?

**Comment by marcusklaas** [comment]
Unfortunately, https://github.com/nrc/rustfmt/pull/111 does not prevent recompilation one when of the test files in `/tests/source/` or `/tests/target/` changes... Any ideas on how we could fix that?

**Comment by cassiersg** [comment]
Yes, I created the symlink by hand (for tests, because `cargo run` recompiled always).
I don't know how to avoid rebuild when a non-source file is touched, but I have maybe an explaination why it occurs: the build script is intended to build external dependencies, but cargo doesn't which files the script builds, so it takes a conservative approach : rebuild if any file changed. If you remove the build script from Cargo.toml, a change in test files doesn't trigger rebuild anymore.
I think the good thing would be to remove the build script, and use something like a deploy script, but it doesn't seem to exist (yet ?). There is maybe another way : cargo is made to recieve build commands from the stdout of the build script, there are maybe commands to indicate dependencies (But at first sight there isn't anything like this in the docs.)

**Comment by marcusklaas** [comment]
Removing the build script sounds good to me. Maybe we can add the default.toml to the root directory in the repository and also add it to `.gitignore`, so that editing it will not register as a change to the repository.

**Comment by nrc** [comment]
Might be worth asking on #cargo about this, seems like there ought to be a solution.

**Comment by marcusklaas** [comment]
It's a known issue: https://github.com/rust-lang/cargo/issues/1162. No known workarounds at the moment. Maybe it's a nice issue to work on.

**Comment by cassiersg** [comment]
Build script was removed by #165.
