### ISSUE TITLE
Box<Trait + Bound> gets reformatted as Box<Trait+ Bound>

### ISSUE THREAD

**Issue by jdm** [nrc/rustfmt#152]
I think it's accidental? It's not a style I've seen elsewhere, at least.

**Comment by marcusklaas** [comment]
For such a seemingly trivial issue, this is surprisingly difficult to repair. When used in generics, i.e.
```rust
fn some_func<T: Box<Trait + Bound>>(val: T) { ... }
```
, the bound `Box<Trait + Bound>` resolves to a [TraitRef](http://doc.rust-lang.org/stable/syntax/ast/struct.TraitRef.html), which can't be further decomposed!

At this point, the only option I see -- and this is what rustfmt does -- is to pass it to rustc's pretty printer. The pretty printer then produces the unexpected outcome.

This really confuses me, because I don't comprehend how the compiler reasons about about the trait bound if its details aren't in the AST at this point. Do you have any pointers, @nrc?

**Comment by nrc** [comment]
From Rustfmt's pov, a TraitRef is just a Path. I think we just farm out formatting paths to the pretty printer. But I don't think we have to do that - we could do it ourselves. It also shouldn't be too hard to fix the pretty printer, presumably this bug manifests when the pretty printer is used.
