### ISSUE TITLE
rustfmt always inserts a blank line at the start of the file

### ISSUE THREAD

**Issue by crumblingstatue** [nrc/rustfmt#190]
Original:
```
fn main() {
}

```

Formatted:
```

fn main() {
}

```

Here is another example:
```diff
*** test.rs.bk	2015-08-18 08:44:28.872288167 +0200
--- test.rs	2015-08-18 08:44:33.888955068 +0200
***************
*** 1,7 ****
--- 1,8 ----
+ 
  use std::fs::File;
  use std::io::Write;
  
  fn main() {
      let mut file = File::create("out.txt").unwrap();
      file.write_all(b"Some text").unwrap();
  }

```
Is this intended, and if so, what is the rationale behind it?

**Comment by nrc** [comment]
I can't really tell from the example. The intended behaviour is that every file ends with a single new line, e.g., the output for your example should be `fn main() {\n}\n`.

I'm not sure of the history here, but that is the widely held convention - e.g., GitHub highlights if you don't end with a newline and some older text editors get confused. I think it makes it is because it makes it easier to run algorithms on a file since very line ends with a newline.

If we are spitting out multiple newlines, then it's a bug.

**Comment by crumblingstatue** [comment]
Oops, I accidentally removed the ending newline from the original code.
The only difference between the two is the empty line at the beginning.

**Comment by nrc** [comment]
Oh I see, *start* of the file - I should have had my coffee before replying. That is indeed unexpected behaviour.

**Comment by sinhpham** [comment]
This is due to the format_missing_inner function not considering the very beginning of the file. Adding the check
```
if start == BytePos(0) {
    return;
}
```
would fix the problem.

**Comment by marcusklaas** [comment]
@sinhpham Good find! Could you create a PR with this change?

**Comment by sinhpham** [comment]
@marcusklaas sure, created. I wanted to post it here first to see if the fix is good (should we directly check for the beginning of the file under format_missing_inner, or should it be somewhere outside of format_missing_inner). I guess my question is wether format_missing_inner being called for the (0, 0) span expected?

**Comment by crumblingstatue** [comment]
This issue still happens in submodules.
Here is an example:

foo.rs
```Rust
mod bar;

```

bar.rs (original)
```Rust
fn doit() {
}

```

bar.rs (formatted)
```Rust
// empty line
fn doit() {
}

```

I request this issue to be reopened.

**Comment by crumblingstatue** [comment]
Thanks, it works fine now!
