### ISSUE TITLE
Unexpected coment added with struct syntax

### ISSUE THREAD

**Issue by Wilfred** [nrc/rustfmt#201]
Given the program:

```rust
fn main() {
    let state = get_state();
    let loop_body_state = ExecutionState { instr_ptr: 0, .. state.clone() };
}
```

Rustfmt generates the program:

```rust

fn main() {
    let state = get_state();
    let loop_body_state = ExecutionState { instr_ptr: 0 /* . */, ..state.clone() };
}
```

I don't think that comment should be there.

**Comment by sinhpham** [comment]
This is due to hard coding the get_lo function to get back 2 positions for StructLitField::Base https://github.com/nrc/rustfmt/blob/master/src/expr.rs#L839, so if there is any space between ".." and the expression, ListItems will think there is a post_comment in the previous field https://github.com/nrc/rustfmt/blob/master/src/lists.rs#L284. I'm unfamiliar with AST in general, so not sure if it retains the location including the ".." string in StructLitField::Base case. Anyone can point me to the right direction?

**Comment by cassiersg** [comment]
That location isn't in the AST (the doc for the AST was at a moment at http://doc.rust-lang.org/syntax/ast, but it isn't there now. You can still build it locally from the git of rust-lang.) Everything you have is the spans of the fields. You can then use find_uncommented (with the span from the end of the previous field to the beginning of the base field) to get the position of the `..`.

**Comment by sinhpham** [comment]
Thanks @cassiersg I think I got a fix, will create a PR tomorrow.
