### ISSUE TITLE
function declarations in extern block not reformatted

### ISSUE THREAD

**Issue by durka** [nrc/rustfmt#299]
If you set `max-width` too low, rustfmt bails on long lines. If you set it too high, it squashes multiline function calls or struct constructions into single lines. There's no middle ground.

**Comment by nrc** [comment]
Could you give some examples please?

**Comment by durka** [comment]
So I have these extern functions, for example

```rust
    fn DMR_GetDevice(pHDev: *mut HDEV, searchMode: DeviceSearchMode, pSearchString: *const c_char, devNr: c_uint, wildcard: c_char) -> TDMR_ERROR;
```

For whatever reason, rustfmt doesn't want to deal with this (i.e. putting in line breaks between the function arguments). It just says the line is too long.

So I set `max-width = 500`. But then it reformats

```rust
Writer { handle: rx.recv().unwrap(),
         dst: Destination::Name,
         other_field: "stuff",
         _ghost: PhantomData
}
```

to

```rust
Writer { handle: rx.recv().unwrap(), dst: Destination::Name, other_field: "stuff", _ghost: PhantomData }
```

which isn't so great.

**Comment by nrc** [comment]
So, not spreading the function signature across multiple lines is very bad - we should do better there, the only thing I can think of is perhaps it being in an extern block means we are skipping it? Should be an easy fix if that is the case.

The struct literal on one line is expected behaviour. There is an option you can set to always use multi-line formatting for struct literals. There is another issue filed some where for setting a maximum number of fields on one line, which should improve things.

**Comment by durka** [comment]
Yeah, if I just paste the function signature into a file and replace the `;` with `{}` then it splits the args. But in an extern block it won't touch it.
