### ISSUE TITLE
Correct indents of imports

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#41]
E.g., 
```
fn foo() {
use Bar;
}
```
=>
```
fn foo() {
    use Bar;
}
```

**Comment by nrc** [comment]
Best way to do this is convert `rewrite_imports` to take an indent and width budget, rather than the current crappy way

**Comment by marcusklaas** [comment]
There doesn't seem to be such a function. There is a `rewrite_use_list`, but that only applies to use lists..

**Comment by nrc** [comment]
Yep, sorry, that was the one I meant

**Comment by marcusklaas** [comment]
I played around a little big with this and I managed to fix the case where the indentation was insufficient, but I cannot seem to reduce indentation. This is difficult because the indentation is not part of the `Span`..

This is not a problem that is specific to imports, by the way. The following will not be rewritten by rustfmt:
```
impl Foo {
        fn some_input(&mut self) {
    }
}
```

Any ideas on how to tackle this?
